import React, { useState, useEffect } from 'react';
import { Video, Play, Clock, FileText, Eye, Sparkles, Download, Palette } from 'lucide-react';
import { VideoScript } from '../../infrastructure/services/AIService';
import CanvasVideoGenerator from './CanvasVideoGenerator';
import { VideoScene } from '../../infrastructure/services/CanvasVideoService';

interface VideoScriptViewerProps {
  moduleTitle: string;
  moduleDescription: string;
  learningObjectives: string[];
  onScriptGenerated?: (script: VideoScript) => void;
}

export default function VideoScriptViewer({
  moduleTitle,
  moduleDescription,
  learningObjectives,
  onScriptGenerated
}: VideoScriptViewerProps) {
  const [script, setScript] = useState<VideoScript | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [expandedScene, setExpandedScene] = useState<number | null>(0);
  const [showCanvasGenerator, setShowCanvasGenerator] = useState(false);

  useEffect(() => {
    // Auto-generate script on mount
    generateScript();
  }, [moduleTitle]);

  const generateScript = async () => {
    setIsGenerating(true);
    try {
      // Import dynamically to avoid circular dependencies
      const { AIService } = await import('../../infrastructure/services/AIService');
      const generatedScript = await AIService.generateVideoScript(
        moduleTitle,
        moduleDescription,
        learningObjectives
      );
      setScript(generatedScript);
      if (onScriptGenerated) {
        onScriptGenerated(generatedScript);
      }
    } catch (error) {
      console.error('Failed to generate video script:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const formatDuration = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const downloadScript = () => {
    if (!script) return;
    
    let scriptText = `VIDEO SCRIPT: ${script.title}\n\n`;
    scriptText += `Description: ${script.description}\n`;
    scriptText += `Duration: ${formatDuration(script.duration)}\n`;
    scriptText += `Generated by: GPT-4 AI\n\n`;
    scriptText += '='.repeat(60) + '\n\n';
    
    script.scenes.forEach((scene, index) => {
      scriptText += `SCENE ${index + 1}: ${scene.title}\n`;
      scriptText += `Timestamp: ${scene.timestamp}\n`;
      scriptText += `\nVISUAL:\n${scene.visual}\n`;
      scriptText += `\nNARRATION:\n${scene.narration}\n`;
      scriptText += `\nON-SCREEN TEXT:\n${scene.onScreenText.join('\n')}\n`;
      scriptText += '\n' + '-'.repeat(60) + '\n\n';
    });
    
    const blob = new Blob([scriptText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${moduleTitle.replace(/[^a-z0-9]/gi, '_')}_script.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const convertScriptToCanvasScenes = (): VideoScene[] => {
    if (!script) return [];
    
    return script.scenes.map(scene => ({
      title: scene.title,
      narration: scene.narration,
      visual: scene.visual,
      duration: 30, // 30 secondes par scène
      onScreenText: scene.onScreenText
    }));
  };

  if (isGenerating) {
    return (
      <div className="bg-gradient-to-br from-purple-50 to-blue-50 rounded-xl p-8 border-2 border-purple-200">
        <div className="flex flex-col items-center space-y-4">
          <div className="relative">
            <Video className="w-16 h-16 text-purple-600 animate-pulse" />
            <Sparkles className="w-6 h-6 text-yellow-500 absolute -top-1 -right-1 animate-spin" />
          </div>
          <div>
            <h3 className="text-xl font-semibold text-gray-800 text-center mb-2">
              Generating video script with GPT-4...
            </h3>
            <p className="text-gray-600 text-center">
              AI is creating a professional script for your module
            </p>
          </div>
          <div className="w-full max-w-xs bg-white rounded-full h-2 overflow-hidden">
            <div className="bg-gradient-to-r from-purple-600 to-blue-600 h-full w-2/3 animate-pulse" />
          </div>
        </div>
      </div>
    );
  }

  // Si le script n'est pas encore généré, afficher l'état de chargement
  // (la génération se fait automatiquement via useEffect)
  if (!script && !isGenerating) {
    return (
      <div className="bg-gray-50 rounded-xl p-8 border-2 border-dashed border-gray-300">
        <div className="flex flex-col items-center space-y-4">
          <Video className="w-12 h-12 text-gray-400" />
          <p className="text-gray-600">Generating script...</p>
        </div>
      </div>
    );
  }

  // Afficher le générateur Canvas si activé
  if (showCanvasGenerator) {
    return (
      <div className="space-y-4">
        <button
          onClick={() => setShowCanvasGenerator(false)}
          className="text-purple-600 hover:text-purple-700 font-medium flex items-center space-x-2"
        >
          <Eye className="w-4 h-4" />
          <span>← Back to script</span>
        </button>
        <CanvasVideoGenerator
          scenes={convertScriptToCanvasScenes()}
          title={script.title}
          onVideoGenerated={(blob) => {
            console.log('Vidéo générée:', blob);
          }}
        />
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl border-2 border-purple-200 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-blue-600 p-6 text-white">
        <div className="flex items-start justify-between">
          <div className="flex-1">
            <div className="flex items-center space-x-2 mb-2">
              <Video className="w-6 h-6" />
              <span className="text-sm font-medium opacity-90">
                {script.type === 'gpt4-script' ? '🤖 Generated by GPT-4' : '📝 Standard Script'}
              </span>
            </div>
            <h3 className="text-2xl font-bold mb-2">{script.title}</h3>
            <p className="text-purple-100">{script.description}</p>
          </div>
          <button
            onClick={downloadScript}
            className="ml-4 p-2 bg-white/20 hover:bg-white/30 rounded-lg transition-colors"
            title="Download script"
          >
            <Download className="w-5 h-5" />
          </button>
        </div>
        
        <div className="flex items-center space-x-6 mt-4">
          <div className="flex items-center space-x-2">
            <Clock className="w-5 h-5" />
            <span className="text-sm">Duration: {formatDuration(script.duration)}</span>
          </div>
          <div className="flex items-center space-x-2">
            <FileText className="w-5 h-5" />
            <span className="text-sm">{script.scenes.length} scenes</span>
          </div>
        </div>
      </div>

      {/* Scenes */}
      <div className="p-6 space-y-4">
        {script.scenes.map((scene, index) => (
          <div
            key={index}
            className="border-2 border-gray-200 rounded-lg overflow-hidden hover:border-purple-300 transition-colors"
          >
            {/* Scene Header */}
            <button
              onClick={() => setExpandedScene(expandedScene === index ? null : index)}
              className="w-full px-4 py-3 bg-gray-50 hover:bg-gray-100 transition-colors flex items-center justify-between"
            >
              <div className="flex items-center space-x-3">
                <div className="w-8 h-8 bg-purple-600 text-white rounded-full flex items-center justify-center font-bold text-sm">
                  {index + 1}
                </div>
                <div className="text-left">
                  <h4 className="font-semibold text-gray-800">{scene.title}</h4>
                  <p className="text-sm text-gray-500">{scene.timestamp}</p>
                </div>
              </div>
              <Eye className={`w-5 h-5 text-gray-400 transition-transform ${expandedScene === index ? 'rotate-180' : ''}`} />
            </button>

            {/* Scene Content */}
            {expandedScene === index && (
              <div className="p-4 space-y-4 bg-white">
                {/* Visual Description */}
                <div>
                  <div className="flex items-center space-x-2 mb-2">
                    <div className="w-2 h-2 bg-blue-600 rounded-full" />
                    <h5 className="font-semibold text-gray-700">Visual</h5>
                  </div>
                  <p className="text-gray-600 pl-4">{scene.visual}</p>
                </div>

                {/* Narration */}
                <div>
                  <div className="flex items-center space-x-2 mb-2">
                    <div className="w-2 h-2 bg-purple-600 rounded-full" />
                    <h5 className="font-semibold text-gray-700">Narration</h5>
                  </div>
                  <div className="pl-4 bg-purple-50 rounded-lg p-3 border-l-4 border-purple-600">
                    <p className="text-gray-700 italic">&ldquo;{scene.narration}&rdquo;</p>
                  </div>
                </div>

                {/* On-Screen Text */}
                <div>
                  <div className="flex items-center space-x-2 mb-2">
                    <div className="w-2 h-2 bg-green-600 rounded-full" />
                    <h5 className="font-semibold text-gray-700">On-Screen Text</h5>
                  </div>
                  <ul className="pl-4 space-y-1">
                    {scene.onScreenText.map((text, i) => (
                      <li key={i} className="flex items-center space-x-2">
                        <Play className="w-3 h-3 text-green-600" />
                        <span className="text-gray-600">{text}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="bg-gradient-to-r from-purple-50 to-blue-50 p-4 border-t-2 border-purple-100">
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <p className="text-sm text-gray-600">
              💡 This script can be used to create a real video with Synthesia, HeyGen, or manually
            </p>
            <button
              onClick={generateScript}
              className="px-4 py-2 text-sm bg-white border-2 border-purple-600 text-purple-600 rounded-lg hover:bg-purple-600 hover:text-white transition-colors"
            >
              Regenerate
            </button>
          </div>
          
          {/* Canvas Generator Button */}
          <div className="flex items-center justify-center">
            <button
              onClick={() => setShowCanvasGenerator(true)}
              className="w-full py-3 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-xl hover:from-green-700 hover:to-emerald-700 transition-all font-semibold flex items-center justify-center space-x-2 shadow-lg"
            >
              <Palette className="w-5 h-5" />
              <span>🎨 Generate video with Canvas (Free)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

